# Generated by Django 5.2 on 2026-06-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_alter_job_experience_level_alter_job_work_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
